### ISSUE TITLE
[Question] Get all contacts w/ Default Params and Email

### ISSUE THREAD

**Issue by AustinTBiggs** [adimichele/hubspot-ruby#106]
I'm attempting to fetch all contacts w/ the Email address, First name, Last name, and Company. 

When I run the following code, all I get is the Email Address. I've looked through the source code, but I'm unsure of how to correctly request the contact properties. How would I tweak my code in order to request multiple properties?

`Hubspot::Contact.all({ property: 'email' }`

**Comment by maxyharr** [comment]
Have you tried passing an array? Worth a shot. 

Hubspot::Contact.all({ property: ['email', 'first_name', etc...] })
