### ISSUE TITLE
Cannot use create_or_update! without passing email in properties

### ISSUE THREAD

**Issue by Nicholas-Horton** [adimichele/hubspot-ruby#108]
...specifically for a set of contacts who do not have a `:vid` or the `:vid` is not known.

The [create_or_update!](https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/contact.rb#L73) function does not remove the`:email` from the `contact_hash`, before converting the `hash_to_properties`.

I am seeing some activity logged on "merged contacts" (whose email has become a comma-separated list of emails), indicating the email is being changed through the API. For some reason, the email never actually changes, despite activity being logged.

I'm not intending to update the `:email` field. Though, I'm not sure how to use `create_or_update!`, keeping the `:email` field as the identifier, without inadvertently modifying contacts where the email does not match up exactly. 

Is the email being intentionally passed in `properties:`, even when the `:email` is being used as the identifier? Any thoughts on whether or not this is an issue? 

I'd be happy to write up a PR. :)

**Comment by cbisnett** [comment]
I suspect what you're seeing is a bug and is related to building the properties hash where we're only excluding the `vid` and not also the `email` ([contact.rb:73](https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/contact.rb#L73)).

My first though was that we should add `:email` to the except call and that would solve this problem but it would also mean that it wasn't possible to use bulk update to update email addresses when the `vid` is known. I'm not sure if updating the email address of a contact is supported when the identifier used is also an email address. This might explain the strange merging behavior you're seeing with email addresses.

Being able to change the email when using a `vid` seems like functionality we should maintain. We could change the `except()` call to exclude both `:vid` and `:email` and only merge the email into the properties hash when the identifier used is a `vid`. This way when creating or updating a contact using the email as the identifier, it won't try to also change the email address.

**Comment by Nicholas-Horton** [comment]
Do you think something like [this](https://github.com/adimichele/hubspot-ruby/compare/master...D3MNetworks:contacts-batch-update/prevents-merged-contact-email-change) gets the behaviour we're looking for? Could refactor a bit to remove the duplication.

**Comment by cbisnett** [comment]
To clean it up a little bit you could move the assignment of `:vid` or `:email` into the hash definition rather than merging on the next line. Something like this:
```
contact_param = {
  vid: contact_hash[:vid],
  properties: Hubspot::Utils.hash_to_properties(contact_hash.except(:vid))
}
```

**Comment by Nicholas-Horton** [comment]
Sounds good. I'll clean it up and open a PR!
