### ISSUE TITLE
Add support for access_token and oauth_token

### ISSUE THREAD

**Issue by wyattbenno777** [adimichele/hubspot-ruby#112]
Great work on this. Are you going to add support for other auth types?
I am using my access tokens from oauth and tweeked connection.rb to use it.

Hapikey is oauth key in my case.

`auth = "Bearer " + Hubspot::Config.hapikey
        response = get(url, headers: { 'Content-Type' => 'application/json', 'Authorization' => auth }, format: :json)`

**Comment by cbisnett** [comment]
I've merged support for this in #70 and I'll release a new version shortly.
