### ISSUE TITLE
Add support for HubSpot Events API

### ISSUE THREAD

**Issue by tuykin** [adimichele/hubspot-ruby#115]
I need [HubSpot Events API](https://developers.hubspot.com/docs/methods/enterprise_events/http_api) in my current project.
Did someone already implemented it? Or is there someone who need that API too?

**Comment by cbisnett** [comment]
PR #119 has some basic support for the Events API. I've requested a few changes and then I'll get it merged. From there we can add any of the other API endpoints you're looking for.

**Comment by fonji** [comment]
PR #208 replaces #119 and includes the requested changes
