### ISSUE TITLE
Errno::ECONNRESET: Connection reset by peer - SSL_connect in Hubspot::Contact.create!("email@address.com", {firstname: "First", lastname: "Last"})

### ISSUE THREAD

**Issue by AZatsepa** [adimichele/hubspot-ruby#118]
Sometimes I get an error when trying to create a contact, although the contact on the Hubspot side is created successfully. I use Ubuntu 16.04 and Ruby 2.4.1. Earlier a similar problem was opened here, but it was closed.
Request Hubspot :: Contact.create_or_update! ([{Email: 'smith@example.com', firstname: 'First', lastname: 'Last'}]) gives the same result.

**Comment by cbisnett** [comment]
There isn't any special SSL or connection management code in the Hubspot class. This error is the result of the remote side of the connection being closed. This isn't an issue with the gem but rather a temporary networking hiccup.

We don't rescue or attempt to handle any networking exceptions. You could catch this an retry using something like [this](https://stackoverflow.com/questions/9204920/how-to-catch-error-connection-reset-by-peer-errnoeconnreset).

**Comment by AZatsepa** [comment]
Thanks, @cbisnett !
