### ISSUE TITLE
SSL Connection Reset in find_by_email

### ISSUE THREAD

**Issue by chimanrao** [adimichele/hubspot-ruby#13]
We keep seeing intermittent errors on the SSL connection getting reset.
The error message reads: Errno::ECONNRESET: Connection reset by peer - SSL_connect.
It keeps happening in the find_by_email call. 

As a user of the API, is there special precautions that we need to take?

**Comment by paulodiniz** [comment]
@chimanrao Can you reproduce this issue? Do you keep getting these errors?

**Comment by cbisnett** [comment]
I'm going to close this issue since there hasn't been any additional information in more than 2 years. If this is still a problem, please reopen the issue. Thanks.
