### ISSUE TITLE
Hubspot Webhooks API

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [adimichele/hubspot-ruby#130]
Is the Webhooks API supported cannot find any documentation?

**Comment by CarolHsu** [comment]
@arnoldmarunda do you mean https://developers.hubspot.com/docs/methods/webhooks/webhooks-overview?

Firstly, you need to create an internal app and initialize the oauth 2.0 flow to install it.
After this, you can start to create an endpoint to listen to the events.
