### ISSUE TITLE
Discussion: API design

### ISSUE THREAD

**Issue by SViccari** [adimichele/hubspot-ruby#154]
Goals to think about as we refactor and add support for new endpoints:

- Avoid leaky abstractions (ex: surfacing HTTParty responses or errors to the gem user)
- Include the Hubspot API error message when a request fails
- Discuss “handling failure” on the README so readers know what to expect when a request fails

--------
Speaking of handling failure... I've been thinking about two ways for this library to express failure: 
1) regard failure as a normal return value (aka, always return a `Response`-like object). This does not apply to the more exception 500-related status codes
2) raise an exception for non-200 response codes.

I'm typically anti-exception and prefer to treat failure as a normal return value. The ruby community, especially those wrapping third-party APIs, strongly favor using exceptions. 

To help us decide, let's consider these design options from the gem user's perspective:
```ruby
# hubspot-ruby returns a Response object
class Account
 def self.update(account_id, params)
   response = Hubspot::Account.update(account_id, params)
   handle_response(response)
 end

 private
 def handle_response(response)
  if response.success?
    response.data
  else
   # error flow (maybe return the errors, log the failed request, etc)
  end
 end
end

# Pros
# - This design encourages gem users to consider error cases
# - Errors are part of the return value, not an exception
# - Favors conditionals over rescuing

# Cons
# - Handling each API response is more verbose as the gem user will call 
#   `response.success?` before accessing `response.data` 
# - This approach is less idiomatic in the Ruby community. Most API wrappers 
#   raise when a request returns an error
```
```ruby
# hubspot-ruby raises for any non-200 response
class Account
 def self.update(account_id, params)
   Hubspot::Account.update(account_id, params)
 rescue Hubspot::Error => exception
   # error flow (maybe return the errors, log the failed request, etc)
 end
end

# Pros
# - This design doesn't require "success?" checks before accessing data. (example)

# Cons
# - Encourages/requires gem users to wrap API calls in a rescue
# - Gem users may forget to wrap an API call in a rescue, resulting in an exception
```

I would love your feedback on which approach (Response vs Exception) seems best to you.

**Comment by chrisbaldauf** [comment]
Sticking with the language and community's idiomatic approach would have the smallest learning curve for folks looking to adopt this gem. Any thoughts on (optionally) wrapping requests in a retry if they hit a 4xx or 5xx (but not 429) error code?

**Comment by cbisnett** [comment]
I think the main reason for using exceptions when working with external APIs is that since it's external you can rely on normal mechanisms for undoing something you've done. For example, with ActiveRecord, you may modify the properties of an instance and change several associated records as part of the change. If something fails, the SQL transaction can be rolled back and everything is undone. With an API that's not possible and it becomes an exceptional case.

I think there is a middle ground we can have here, which follows the Ruby (Rails?) conventions. Having an `update()` method that returns false on error while also having an `update!()` method that raises an exception on error.

**Comment by cbisnett** [comment]
An issue with wrapping requests automatically in a retry loop is that this may exacerbate any issues and potentially start triggering rate limiting by HubSpot. I think it's better for the user of the gem to decide for each request if they want to retry based on the failure type. If the failure is expressed as a specific exception class, these can easily be retried with existing functionality in things like ActiveJob or handled cleanly with Rails features like `rescue_from`, or with a simple Ruby `begin...end` with a `retry` statement. This gives the user of the gem more flexibility to explicitly retry a failed request.

**Comment by SViccari** [comment]
Thank you all for your feedback! I'm going to close this issue as I think we're in agreement on the following:

Design Decisions:
- Avoid leaky abstractions (ex: surfacing HTTParty responses or errors to the gem user)
- Include the Hubspot API error message when a request fails. We want to pass along all insight that's provided by the HubSpot API.
- The library will raise for any non-200 response
- Discuss “handling failure” on the README so readers know what to expect when a request fails and how best to rescue
