### ISSUE TITLE
Undefined method `update!' for Hubspot::Deal:Class

### ISSUE THREAD

**Issue by Joemarc** [adimichele/hubspot-ruby#180]
Hello first of all good job with this gem ! :)

Everything is working fine, except that on my side i can't update a deal 
`undefined method `update!' for Hubspot::Deal:Class` is the message i get when i try to update a deal

`Hubspot::Deal.update!(deal_id, pipeline: 'default', dealstage: 'closedwon')`

I have the latest version of the gem : 
`gem 'hubspot-ruby', :git => 'https://github.com/adimichele/hubspot-ruby.git', :branch => 'v0-stable'`
`hubspot-ruby (0.6.1)
      activesupport (>= 3.0.0)
      httparty (>= 0.10.0)`

May be i did something the wrong way ?

Thanks in advance :)

**Comment by cbisnett** [comment]
The v0.x branch has a number of inconsistencies when it comes to methods defined for different Hubspot resources. In this case, `update!` is only defined for an instance and not for the class. This is something I'm fixing for the v1.x release. Until that's released this should work for you:
```ruby
deal = Hubspot::Deal.find(deal_id)
deal.update!(pipeline: 'default', dealstage: 'closedwon')
```

**Comment by Joemarc** [comment]
Thanks a lot :)
