### ISSUE TITLE
Support for Contact Update API

### ISSUE THREAD

**Issue by ngsikai** [adimichele/hubspot-ruby#191]
Looking through the contact codebase on `master` there is an `UPDATE_PATH`:

![Screen Shot 2019-03-21 at 9 45 12 AM](https://user-images.githubusercontent.com/6193290/54729383-2ea5d480-4bbe-11e9-891c-3683c6cea8b7.png)

However, it doesn't look like it's used anymore. Are there plans to support the update by vid or email endpoints? https://developers.hubspot.com/docs/methods/contacts/update_contact-by-email

**Comment by cbisnett** [comment]
I'm in the process of implementing this functionality which is why the path is listed but there are no references to it. It will be added to `master` shortly.
