### ISSUE TITLE
Saving a contact fails with "undefined method 'with_indifferent_access' for nil:NilClass (NoMethodError)"

### ISSUE THREAD

**Issue by kitebuggy** [adimichele/hubspot-ruby#193]
This HubSpot API [contact update endpoint](https://developers.hubspot.com/docs/methods/contacts/update_contact) does not respond with the updated contact, just with a response code.

Trying to save a changed contact record will therefore fail [here](https://github.com/adimichele/hubspot-ruby/blob/dd1573a80247e2bfb876ffed3c8c004b6dd24045/lib/hubspot/resource.rb#L110) when trying to parse the nil body response.

**Comment by cbisnett** [comment]
This is something I ran into when I was implementing `update` for both instances of `Resource` and for the class level method. The API endpoints aren't consistent. I found some endpoints that will return only a success code, some that will return all the properties of the updated resource, and others that will return only the updated properties.

I've been thinking about the best path forward and I think one of the goals of the library is to provide an interface to the APIs that is consistent even if the API endpoints are not. So I'm thinking the lowest common denominator is likely what will have to be used here and assume that all endpoints only return a success code. From there we can merge in the changed properties. If the user wants the full property details including the updated history and other metadata associated with the property then they'll have to call `reload`.

I hadn't realized this would also be broken with save and there aren't enough tests to cover all the new functionality yet so thank you for submitting a ticket. I'll take a look at this and will likely fix this as part of handling updates.
