### ISSUE TITLE
ContactList Find Parses as Int

### ISSUE THREAD

**Issue by Welfordian** [adimichele/hubspot-ruby#198]
Hi,

I’m trying to use `Hubspot::ContactList.find` to get a list of recently updated contacts but it’s parsing the arguments to integers which makes it so the following does not work.

`Hubspot::ContactList.find("recently_updated/contacts/recent")`

Any way around this?

**Comment by cbisnett** [comment]
The interface is designed to accept an Integer or String representation of an Integer (eg "1"). Requesting recently updated contacts will require another method to call a different Hubspot API endpoint. Passing a URL here isn't how the interface is designed.
