### ISSUE TITLE
Status of this Project

### ISSUE THREAD

**Issue by leifg** [adimichele/hubspot-ruby#202]
It has been raised in multiple PRs and issue and in issue #94 there has been a lot of people offering help for this gem. However that conversation is now almost 1 year old so I was wondering what the update is.

If this is project is not maintained anymore, is there any fork that is still under maintenance?

**Comment by cbisnett** [comment]
Based on the comment you linked I was given commit access. I’ve been working on updating this project to standardize the interfaces and make it easier to work with overall. Is there something specific you’re looking for that isn’t implemented?

**Comment by leifg** [comment]
Thank you for your reply.

Specifically I am looking for creating/updating products and line items.

More generally: the master branch is ahead of the latest release and has some significant changes. It would be great if I knew that the master changes would be going into a release at some point so I can stop using the github repo in my Gemfile.

**Comment by cbisnett** [comment]
Yes there is still some work to be done to convert existing classes to using the Resource model. Additionally there may be some changes to the implementation as we make updates and find things that don't work or are ugly. Once done we'll release v1.0. If you're using master you'll want to be careful and test your use of the library.
