### ISSUE TITLE
Hubspot depreciated v2 of Blog Topic API

### ISSUE THREAD

**Issue by zentrification** [adimichele/hubspot-ruby#21]
Starting seeing this error today

[1] »  Hubspot::Topic.list
Hubspot::RequestError: Response body: <!DOCTYPE html>
...
HubSpot - Page not found

I have an email from them back on April 24, 2015 announcing Blog Topic API v3, which mentions v2 being depreciated around June 15th.

**Comment by paulodiniz** [comment]
Closing this issue because the code is merged
