### ISSUE TITLE
Hubspot::Contact.find_by_email generating error not returning nil

### ISSUE THREAD

**Issue by csalvato** [adimichele/hubspot-ruby#33]
``` ruby
hubspot_contact = Hubspot::Contact.find_by_email email
```

Having problems with this code above.  When the contact is not found, I was expecting it to be `nil`.  Instead, I am getting a `Hubspot::RequestError`

```
Hubspot::RequestError: Response body: {"status":"error","message":"contact does not exist","correlationId":"e378d2f2-57f9-4e60-93ab-269681d419d4","requestId":"0043a897-2017-4735-945e-5ecad6fbe9cd"}
from /Users/csalvato/.rvm/gems/ruby-1.9.3-p551@powersupply/gems/hubspot-ruby-0.1.8/lib/hubspot/connection.rb:9:in `get_json'
```

In my code, I am trying to use begin -> rescue blocks, but that doesn't seem to be catching the error for proper handling either.

**Comment by csalvato** [comment]
Here's the full code to show how the error handling is also not working:

```ruby
def change_hubspot_properties
    email = self.orders.last.user.email
    geo = self.orders.last.location.store_front.name
    begin  
      hubspot_contact = Hubspot::Contact.find_by_email email
      hubspot_contact.update!({lifecyclestage: "customer", geo: geo})
    rescue Exception => e 
      if (e.message == "contact does not exist")
        first_name = self.orders.last.user.first_name
        last_name = self.orders.last.user.last_name

        hubspot_contact = Hubspot::Contact.create!(email, {firstname: first_name, lastname: last_name})
        hubspot_contact.update!({lifecyclestage: "customer", geo: geo})
      end
    end 
  end
  handle_asynchronously :change_hubspot_properties
```

**Comment by paulodiniz** [comment]
@csalvato I tried a different version of the code, and the rescue happens.

1 - What version are you using?
2 -  Please try this code

```
require 'bundler/inline'
require 'active_support'

gemfile do
  source "https://rubygems.org"
  gem 'activesupport'
  gem 'hubspot-ruby'
end

Hubspot.configure(hapikey: "test")

begin
  Hubspot::Contact.find_by_email 'doesnot@exist.com'
rescue Exception => e 
  puts "RESCUED"
end
```

**Comment by csalvato** [comment]
I'm not exactly sure what was causing the error but this is now resolved.  I am using the following (slightly modified) code, if it helps anyone

```ruby
def change_hubspot_properties
    email = "some@example.com"
    geo = "NYC"
    begin 
      hubspot_contact = Hubspot::Contact.find_by_email email
      hubspot_contact.update!({lifecyclestage: "customer", geo: geo})
    rescue Exception => e 
      if e.message.include? "contact does not exist"
        first_name = "First"
        last_name = "Last"

        Hubspot::Contact.create!(email, { firstname: first_name, 
                                          lastname: last_name,
                                          lifecyclestage: "customer",
                                          geo: geo })
      end
    end
  end
```

As a sidenote, the README.md should be updated to reflect that a non-existant customer throws an error.  Right now the README says it returns `nil` which isn't how it works. :)

**Comment by paulodiniz** [comment]
@csalvato Will work on that :+1: Thanks

**Comment by trivett** [comment]
Anyone working on this fix? I can if nobody else is free. I think the exception block i am not the only one apparently using to make find_by_email return nil if its a new contact. Perhaps a version of `find_or_create_by` method?

**Comment by dan987** [comment]
@trivett sound like you got a backward compatible fix in mind.  Go for it.

**Comment by cbisnett** [comment]
Any interest in this still?

**Comment by cbisnett** [comment]
Looking at the code as it exists today, it's catching any exceptions and returning `nil` if the exception message contains `not exist` which should correctly catch errors where the contact doesn't exist as long as the error message hasn't been changed. This code could be improved upon but I think we can save that for the v1.0 rewrite.

If you find this isn't working, please reopen the issue.
