### ISSUE TITLE
No OAuth?

### ISSUE THREAD

**Issue by justinxreese** [adimichele/hubspot-ruby#39]
It looks like OAuth is the preferred way to connect to the API but that is not documented anywhere. Is it supported? I am not able to get a plain API key.

**Comment by BastienL** [comment]
@justinxreese see https://github.com/adimichele/hubspot-ruby#note-about-authentication

**Comment by coxw** [comment]
Note: this is going to be required now if you plan to make an app with Hubspot: https://integrate.hubspot.com/t/announcement-new-apps-will-only-work-with-oauth-2-0/1960

**Comment by blakewest** [comment]
@BastienL @justinxreese I added an early PR for this here: https://github.com/adimichele/hubspot-ruby/pull/70 .

**Comment by cbisnett** [comment]
Some initial support for OAuth has been merged in #70.
