### ISSUE TITLE
Form API Submission Format

### ISSUE THREAD

**Issue by dinosimone** [adimichele/hubspot-ruby#40]
It appears that the form submission is encoded as JSON. While it will post successfully, it creates an entry with no contact information. According to the [API documentation](http://developers.hubspot.com/docs/methods/forms/submit_form), the form fields should be URI encoded.

opts[:body].to_json should be changed to URI.encode(opts[:body].map{|k,v| "#{k}=#{v}"}.join("&")) inside submit of FormsConnection < Connection.

**Comment by lime** [comment]
Hm, it looks to me like this was fixed in #20, quite some time ago.

However, it also looks like the latest release (0.1.18) is over a year old, so that fix is unreleased at the moment. Could any of the maintainers shine some light on this, will there be a new release?

**Comment by dinosimone** [comment]
Yeah, you're right. Looks like it was fixed and never released. Currently have to run a locally patched version unfortunately.

**Comment by afestein** [comment]
If you're using bundler, you can circumvent that issue by using the latest code directly from this repo:
`gem 'hubspot-ruby', git: 'https://github.com/adimichele/hubspot-ruby'`

**Comment by SViccari** [comment]
Hi everyone, I'm closing this issue as the fix was released and the latest gem version available is `v0.6.1`. 🌻
