### ISSUE TITLE
Publish newer versions?

### ISSUE THREAD

**Issue by swifthand** [adimichele/hubspot-ruby#48]
The latest version available on rubygems.org is 0.1.8, and `master` currently sits at 0.1.12.

Concrete motivation for this request is the `Contacts::find_by_email` method. In the latest published version, the "batch mode" branch of logic within that method has a comment which reads `TODO: Transform response`, and fails to produce `Hubspot::Contact` instances.

The current version of [`contact.rb`](https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/contact.rb#L76) _does_ consistently produce `Hubspot::Contact` instances in both batch and non-batch mode. This was added in 5fcfcabfb19cd2ba679a1f50e74794bd99e408d7 and it looks like any release beyond 0.1.8 (even just 0.1.9) would address this.

**Comment by dan987** [comment]
Just attempted to publish as a moderator & do not have permission - we need an owner to publish a new version.

**Comment by adamcrown** [comment]
I'd appreciate this too. I need the `Hubspot::Owner` class for my app.

@adimichele or @paulodiniz would either of you mind releasing a new version of the gem? It looks like you both have access. Thanks.

**Comment by adimichele** [comment]
Done. I haven't used Hubspot in years so I can't guarantee this will work in production. It would be best if an active contributor takes over `gem push` responsibility...

**Comment by adamcrown** [comment]
@adimichele thanks so much for the quick response. Much appreciated.
