### ISSUE TITLE
Batch

### ISSUE THREAD

**Issue by ManuelFrigerio** [adimichele/hubspot-ruby#51]
Hi, 

According to this Hubspot article (http://developers.hubspot.com/docs/faq/working-within-the-hubspot-api-rate-limits) it would be better to batch requests.

How do I do that with your gem?
Thanks

**Comment by coxw** [comment]
@ManuelFrigerio You can do batch requests via contacts now.  Check out Contact::create_or_update! here https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/contact.rb#L61-L79
