### ISSUE TITLE
Missing rake folder in public gem

### ISSUE THREAD

**Issue by JeremyLopez** [adimichele/hubspot-ruby#56]
After installing the gem I was unable to deploy my app due to the following rake error:

```
rake aborted!
LoadError: cannot load such file -- /Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/gems/hubspot-ruby-0.2.0/lib/tasks/properties.rake
/Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `block in load'
/Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/gems/activesupport-4.2.2/lib/active_support/dependencies.rb:268:in `load'
/Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/bin/ruby_executable_hooks:15:in `eval'
/Users/jeremylopez/.rvm/gems/ruby-2.2.3@awaken/bin/ruby_executable_hooks:15:in `<main>'
```

After navigating to the location of the gem, the lib folder had no tasks folder.  After specifying in my gemfile to pull directly from your repo, everything worked.  Figured this might be helpful to someone.

**Comment by coxw** [comment]
@adimichele I think this has something to do with the Gemspec, right? https://github.com/adimichele/hubspot-ruby/blob/master/hubspot-ruby.gemspec#L8-L9  Tasks folder just isn't there, so anyone who tries to install will get an error that the properties.rake file doesn't exist.

**Comment by adimichele** [comment]
Thanks guys. Please give the updated gem a try.
