### ISSUE TITLE
Cannot page through all contacts

### ISSUE THREAD

**Issue by coxw** [adimichele/hubspot-ruby#57]
https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/contact.rb#L33-L46

The Hubspot API has the idea of batching requests (typically max of 100 contacts at a time), and the all() method currently only returns back Contact objects, but it doesn't let you know if "has-more" (true/false) or "vid-offset" to make that in the next request.  This means, all() will only reliably ever return 100 contacts max.

**Comment by coxw** [comment]
PR: https://github.com/adimichele/hubspot-ruby/pull/58

**Comment by cbisnett** [comment]
Closing this since the PR was merged.
