### ISSUE TITLE
Properties API not allowing to create property with 'date' as datatype

### ISSUE THREAD

**Issue by titame** [adimichele/hubspot-ruby#69]
I am trying to create property with date as datatype in Hubspot through contact properties API. But it is raising error `Invalid type : date` when I make API call to create property using following API method -

`Hubspot::ContactProperties.create!({params})`

Seems this issue is due to following definition of PROPERTY_SPECS constant in `hubspot/properties.rb` where `date` is not listed in `valid_types` -

PROPERTY_SPECS = {
      group_field_names: %w(name displayName displayOrder properties),
      field_names:       %w(name groupName description fieldType formField type displayOrder label options),
      valid_field_types: %w(textarea select text date file number radio checkbox),
      valid_types:       %w(string number bool datetime enumeration),
      options:           %w(description value label hidden displayOrder)
}

Although `date` is listed as valid datatype in Hubspot contact properties API - http://developers.hubspot.com/docs/methods/contacts/v2/create_contacts_property

Do we need to add `date` as valid type here?

Any help will be highly appreciated.

Thank you.

**Comment by masonnl** [comment]
@titame I was having the same issue on my end. I allowed the `date`  property to the constant and the API requests are successful. I also allowed `booleancheckbox` and those requests were successful as well. This may be worth a pull request. Thank you for the link to their docs. Looks like a few other fields could be allowed as well.

**Comment by titame** [comment]
Yes @masonnl . I did the same way to make API request successful :)
