### ISSUE TITLE
Hubspot::Contact.create_or_update!(contacts) outputs "/contacts/v1/contact/batch/?" to console

### ISSUE THREAD

**Issue by retorquere** [adimichele/hubspot-ruby#78]
calling `Hubspot::Contact.create_or_update!(contacts)` outputs `"/contacts/v1/contact/batch/?"` to console. Is it possible to disable this? I'm using this in a cron job; cron jobs send the output by mail if there is any, so I'm getting frequent emails for this.

**Comment by jeisenberg** [comment]
+1 - can we please disable this? It is clogging up logs.

**Comment by dan987** [comment]
@retorquere || @jeisenberg submit pr.

**Comment by cbisnett** [comment]
This issue was fixed back in December 2016 but no new gem was released. Today I release v0.3.0 with this fix and others and verified this no longer outputs the URLs.
