### ISSUE TITLE
Gem fails to initialize on Windows

### ISSUE THREAD

**Issue by gipnokote** [adimichele/hubspot-ruby#88]
lib/hubspot/config.rb:

`DEFAULT_LOGGER = Logger.new('/dev/null')`

This line causes a problem when the gem is initialized via Gemfile. This is because doing this on Windows will result in the exception:
`No such file or directory @ rb_sysopen - /dev/null (Errno::ENOENT)`

The better, platform independent approach is to use it like this:
`DEFAULT_LOGGER = Logger.new(nil)`

This would fix the problem.

P.S. I still don't like that we are instantiating a new Logger instance during gem initialization. This is just not needed at this point.

**Comment by dan987** [comment]
Thanks for this, I would suggest submitting a pr
