### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by cbisnett** [adimichele/hubspot-ruby#94]
At Huntress Labs we use this gem to integrate with our HubSpot instance. I see there are several issues filed and a number of pull requests waiting to be reviewed and merged. I would like to help out maintaining this project since it's important to us. Would you mind adding me as a maintainer or would it be easier if we just fork the repository?

cc: @dan987

**Comment by dan987** [comment]
@cbisnett @adimichele would appreciate the help!

**Comment by cbisnett** [comment]
Great! I think it’ll probably be more helpful for me to be a maintainer so I can approve and merge pull requests rather than for me to add to the backlog of existing pull requests. What do you think?

**Comment by adimichele** [comment]
Yes! Would love to get your help maintaining. I haven't used Hubspot in like 4 years so I do not actively maintain anymore. Would you like `gem push` privs as well?

**Comment by cbisnett** [comment]
Great, I look forward to helping to maintain the project. Privileges to push new versions of the gem would be fantastic since right now we've had to clone our repo with patches into our Rails vendor folder.

**Comment by adimichele** [comment]
I need to know which email you use to log in to rubygems in order to add you. Not sure of the best way to send that to me without exposing it to the public. Do you want to encrypt it with my PGP key?

**Comment by cbisnett** [comment]
Sure that can work. If you post the public key here, I'll encrypt and post the blob.

**Comment by cbisnett** [comment]
Can you give me the permissions required to setup testing with Travis CI?

**Comment by adimichele** [comment]
My pgp key is below. What permissions do you need to set up TravisCI? Are you able to set up an integration here? https://github.com/adimichele/hubspot-ruby/settings/hooks/new?service=travis

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFnpei8BCADojt4SqU0v8BdOBDK0rGDoWfYOatPf30RdE1p0QSfckO0bKnHN
eGa20oVSbo9qa5GbeArJT/w2KpLmN7gQCyWP1vjSZIV88QYTdCdSx0O4eSmakdT5
5nDwk7JdNHZPXQsz9xBXK6glpUXPONu2UOnbUJxApicJxizcarMC3Ejc/3B3m1eX
25Rno3c7XdsVXHfQ4MKzAJ70Hipigol3Q31SxzC0354M7o8Dgo5JIx1KQ5thUFhb
ONiTIzlQbla7DtX0lCO0eV2RedqasE2FgYjMDR6E7uxXS01zXu0oIwTr9cxv6iaJ
f9hsy1mzGl5+Dsf1to9lsjA3clFku7kaBFIFABEBAAG0JEFuZHJldyBEaU1pY2hl
bGUgPGFkaW1pY2hlbGVAZ2l0aHViPokBTgQTAQgAOBYhBLcX7uUFcmEKC3KRh7qs
GpOWuhoNBQJZ6XovAhsDBQsJCAcCBhUICQoLAgQWAgMBAh4BAheAAAoJELqsGpOW
uhoN7NgH/3M1oPZRgQC4xtMT8wFGgHKUXnD9ZpIUgaV2Q3gCXfZ8i4h8ugwz02jm
UDpgH70lDBRQrm5knh/gYHujEir1u4pvaqkdwhii68RUHICd4O4fGSUr2y5t8vTo
j9+8SDVMJpPzngT13KdIIJIF4mw//4L76TofiZQho0F+DTPw79TemQL9XcJW3Zq+
aDe2bWpIUXGberjx9/QS4fTxaMuz1IPYmz864nt871nKsLBd5kBIdbUHgXeRZTBp
Gv9iX9gRAgFIRoTjjF6bCI+Inub/+Xk1Krv3Gz+UkSxKDNf+CafVxLRQsOSea8O6
8KaNYdvBuADnaIzbByh+fnqX29wZFZy5AQ0EWel6LwEIAM3DZxhvbY7xZnCESDu/
ckpboDUCl2BTG6oYix3M1whLOifm1yUVosY/uGKNIEzWIo4Cbl07Cb2i52cgklMT
vzAFoK9NL1Fp0Ak4aP1lFRbGHtqZcC9fXnqiCY/1H2CKg8n0ysWmOAwyfbFmj+W2
xT7SGuDgAXovkiTijfszPtGgXXrLgZhCZYLP5H5CQRdRQRrsNcNtUxeiA9BMHDmH
cS0HkG+vQvHz+FnB0LVVaNfzNHxOCAllyVWehgZeOb1FdM+HUL9JmE0lpwQ5VJhr
vGcbYf/NRFdhzf6lkLYCIAby5yugnxwkKN9+1AzlEIgQVvUrYaYX5L46bT+I03fq
nHsAEQEAAYkBNgQYAQgAIBYhBLcX7uUFcmEKC3KRh7qsGpOWuhoNBQJZ6XovAhsM
AAoJELqsGpOWuhoN3wIIAIKv+yL+OouypQRkiKnKH/E8xjlsY9JLqjE+iCQ9jNh/
Wd/1IP+ZT80P99Zza3yh22vY9cuN4GFKDMDBQhBNGYqbdQj24maN/K6K8E9pnhLC
zUhshR2TIYtDOTjCs7BujLRZeI0r1NMHZlKFB0W+Nmrilgrbj51dLqV8+ShJoybh
s+ErIu8qFH9FTkz3t4ZYBT049hsFDIYd7pfIKg6w+ednK9BNOMtpeTOaug1DSLiX
8EZOZ4kAdvAudrXyW5v81PqSyHU6ZbZ4bCSdDQAodjPi6aFD12Bv7GgslyOl3HFx
agE3oZabpXFPyM5Mpr6EsemypnmcpdY49v+u/PXuTGE=
=CVwF
-----END PGP PUBLIC KEY BLOCK-----

**Comment by cbisnett** [comment]
I'm not sure exactly what permissions you need but I can't get to the page you posted or the settings for this repository. I've never setup Travis CI on a shared repository before so I'm not sure.

-----BEGIN PGP MESSAGE-----

hQEMAz5SvTXAw+ViAQf/RR1YrbY5XxYiGsVMHTD/ol6vrG7BUTA+2inUv8PG3Pft
qe5XgjPs//F08Kswn+fgDpmziaVwJhBVkOiPIJbWWhfy1ZT8KqFyguE+dgaWdZDy
vyXLU752GWBMF8/pnUSK3tQ9zeh69d2hpRjT4uLCcy8PcNxc+zyKSsdz2i5AsxYy
9zoTx4X9YT+I6Pyp0ebMO7Q5hQo/JLFpYZx37SFZTeAkgeQTY5xzD33opmFQOv3m
FUrwe4mZdnXHNBxx5iJ6aLkwNBfidf094Uf9ofjX7hBtD8fg5krrF4zUjkRtPb5v
DLc8esjPUgDoWNOKaheGOjHnP7wi6Xts0DOb8Ni6ldJqAdNq/y9c/LgUwhxRkLMy
BzCeEWwRx/V8h6l1FeojNmkoyu5YrMMR7Y0AysJ/LuKK2JRsoy/2eQ9drjz9ApVw
VVgDiYHolPqWitjjlHEdJpuMPECh4G77KYvxADd47LDFcSZ9ke8/pR+8iQ==
=GJpm
-----END PGP MESSAGE-----

**Comment by adimichele** [comment]
I just added you as a gem owner. You should be able to push new versions now.

I've never set up TravisCI before either. It looks like I can add the webhook manually with a "User", "Token", and "Domain". Do you have that?

**Comment by cbisnett** [comment]
It looks like I would need write access to add webhooks. I couldn’t find any way to manually setup the integration. Travis-CI syncs your repos and does the setup through the API. I don’t think their end would work if we only created the webhook.

I’ll verify that I can push new versions of the gem and get out a new version soon since there are several fixes on master but not published.

**Comment by cbisnett** [comment]
Here is their documentation about which permission scopes they require: https://docs.travis-ci.com/user/github-oauth-scopes/

**Comment by adimichele** [comment]
hmm. according to this, all of your repos should show up in Travis:
> read:org (read-only) When you’re logged in on Travis CI, we show you all of your repositories, including the ones from any organization you’re part of. The GitHub API hides any organizations you’re a private member of without this scope. So to make sure we show you all of your repositories, we require this scope. Note that this scope allows access to the basic information about both private and public repositories, but not on any of the data or code stored in them.

I wonder if this only shows repos that you own or are owned by an organization you're a part of? If that's the case, then either I have to set up Travis or we have to create an organization you're a part of and move this repo over there.

What do you think?

**Comment by adimichele** [comment]
If you and Huntress Labs are committed to maintaining this, I'm OK moving project ownership over to you guys. It's probably better off in your hands anyways since I really don't contribute anymore. How does that sound?

**Comment by cbisnett** [comment]
Yeah we are committed to maintaining and updating this code for the foreseeable future. We make pretty good use of the features of Hubspot so we’ll be using this to integrate our sales pipeline with our product. How do we get this moved?

**Comment by markitecht** [comment]
Hey folks I run Product at HubSpot ... how can we help this project?

**Comment by adimichele** [comment]
@markitecht Does HubSpot want to officially support this gem? Might be worth a quick call to talk about it. I can give you some history, and if HubSpot would like to get involved we can talk about the best way to maintain this. Let me know your thoughts.

You can reach me on LinkedIn if you'd like: https://www.linkedin.com/in/andrewdimichele/

**Comment by cbisnett** [comment]
Any interest in setting up a call? I would like to stay on and help update and maintain the project. Like I said previously, Huntress Labs uses this project throughout our product to inform our sales reps and update the pipelines. There are a few things I've done in the short time I've been helping out and I had some plans for what I felt needed to be changed/updated to bring the library inline with the current API and make it more usable.

**Comment by dan987** [comment]
Do not need to be on the call and can't contribute as much as @cbisnett but would like to keep active role with the project as well.  Whoever ends up with it.

**Comment by cbisnett** [comment]
@markitecht: Do you still want to setup a call to discuss Hubspot support of the project?

**Comment by kitebuggy** [comment]
Is this gem still being maintained or is it now in limbo?

**Comment by cbisnett** [comment]
It's still being maintained but it goes through alternating phases of action and stagnation. Currently it's getting a bunch of external attention but I've been really busy so I haven't been able to get to all the issues and PR's.

**Comment by elizabth** [comment]
Hey everyone, wanted to pop in and say hi. I'm the new dev rel lead at HubSpot. I'd love to connect with everyone interested in maintaining/contributing to this gem. We definitely want to figure out how we can better support you (and our larger community). If anyone would be up for hopping on a call with our team - lmk. Also happy to just be a resource in general at HubSpot.

**Comment by gregblass** [comment]
Hey @elizabth! I'm about to set out to implement a multi-tenant implementation of this gem. It looks like there is an open PR to add OAuth support - but it seems to have feel to the wayside.

Just curious - with HubSpot being the size that it is - are there no plans to internally help maintain this gem / add features on HubSpot's end?

**Comment by gregblass** [comment]
There also looks to be some open PR's that seem pretty simple and aren't causing conflicts, like #116. Wondering if there's any way to start getting those merged?
