### ISSUE TITLE
Recent created contacts

### ISSUE THREAD

**Issue by diwu86** [adimichele/hubspot-ruby#98]
HI, I see we have [this](https://github.com/adimichele/hubspot-ruby/blob/master/lib/hubspot/contact.rb#L20) for recently updated contacts. Do we have an endpoint that will return recently created contacts? If not, can I submit a pr to support this? We need this endpoint to bring down our call numbers to Hubspot. We are close to the limit. Thanks.

**Comment by diwu86** [comment]
any updates on this one? I already have a pr to support this endpoint? Can someone review? Thanks

**Comment by cbisnett** [comment]
Sorry it took a while. I've reviewed and merged your pull request. Thanks for writing that up. I've just pushed v0.4.0 to Rubygems so you should be able to update and get the newest version.
